version: "3.9"

services:
  backend:
    build: .
    container_name: cash-clever-backend
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=development
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
