name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Chỉ chạy khi push/merge vào main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest -v

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version info
        id: vars
        run: |
          echo "sha_short=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT
          # Nếu đây là commit được tag, lấy tag làm version
          if [ -n "$GITHUB_REF_NAME" ]; then
            echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "version=${sha_short}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            lotusreichhart/cash-clever-backend:${{ steps.vars.outputs.version }}
            lotusreichhart/cash-clever-backend:${{ steps.vars.outputs.sha_short }}

  # -----------------------------
  # Deploy server (comment lại vì chưa có server)
  # -----------------------------
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: docker
  #   steps:
  #     - name: Deploy to Server via SSH
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         key: ${{ secrets.SSH_KEY }}
  #         script: |
  #           cd /app/cash-clever-backend
  #           docker pull lotusreichhart/cash-clever-backend:${{ steps.vars.outputs.sha_short }}
  #           docker tag lotusreichhart/cash-clever-backend:${{ steps.vars.outputs.sha_short }} cash-clever-backend:current
  #           docker-compose -f docker-compose.prod.yml up -d --force-recreate
